server:
  port: ${PORT:8084}

spring:
  application:
    name: progreso-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false
    hostname: ${RAILWAY_PRIVATE_DOMAIN:localhost}