package com.tdis.common.enums;

public enum PublicoObjetivo {
    SOLO_ALUMNAS,
    SOLO_ALUMNOS,
    SOLO_DIVISION_INDUSTRIAL_Y_NANOTECNOLOGIA,
    SOLO_DIVISION_ECONOMICO_ADMINISTRATIVA,
    SOLO_DIVISION_TECNOLOGIAS,
    SOLO_DIVISION_IDIOMAS,
    TODAS_LAS_DIVISIONES
}