server:
  port: ${PORT:8083}

spring:
  application:
    name: tramites-service
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  web:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: on_param
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/tdis_tramites}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    "service-url":
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false
    hostname: ${RAILWAY_PRIVATE_DOMAIN:localhost}

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 5000

n8n:
  webhook:
    url: ${N8N_WEBHOOK_URL:http://192.168.1.188:5678/webhook-test/3df73d6f-6d77-4cda-9ccd-5bf25a85a17f}